-- Inserindo dados na Tabela Seleção --
desc Selecao;

INSERT INTO Selecao VALUES ('Argentina', 'Seleção Argentina', 'TrabalhoFinalI/Etapa3/Bandeiras/Argentina.png', 'América do Sul', 'Oíd, mortales, el grito sagrado¡Libertad! ¡Libertad! ¡Libertad! Oíd el ruido de rotas cadenas Ved en trono a la noble igualdad', 'B');
INSERT INTO Selecao VALUES ('Bolívia', 'Seleção Boliviana', 'TrabalhoFinalI/Etapa3/Bandeiras/Bolívia.png', 'América do Sul', 'Bolivianos: El hado propicio Coronó nuestros votos y anhelo Es ya libre, ya libre este suelo Ya cesó su servil condición Al estruendo marcial que ayer fuera', 'A');
INSERT INTO Selecao VALUES ('Brasil', 'Seleção Brasileira', 'TrabalhoFinalI/Etapa3/Bandeiras/Brasil.png', 'América do Sul', 'Ouviram do Ipiranga as margens plácidas De um povo heroico o brado retumbante E o sol da liberdade, em raios fúlgidos Brilhou no céu da pátria nesse instante', 'A');
INSERT INTO Selecao VALUES ('Catar', 'Seleção do Catar', 'TrabalhoFinalI/Etapa3/Bandeiras/Catar.png', 'Ásia', 'Qasamā"an, Qasamā"an Qasamā"an biman rafa" as-samā" Qasamā"an biman našra aẓ-ẓīyā" Qaṭar"un satabaqī ḥūrrat"an', 'B');
INSERT INTO Selecao VALUES ('Chile', 'Seleção Chilena', 'TrabalhoFinalI/Etapa3/Bandeiras/Chile.png', 'América do Sul', 'Puro, Chile, es tu cielo azulado Puras brisas te cruzan también Y tu campo de flores bordado Es la copia feliz del Edén Majestuosa es la blanca montaña Que te dio por baluarte el Señor', 'C');
INSERT INTO Selecao VALUES ('Colômbia', 'Seleção Colombiana', 'TrabalhoFinalI/Etapa3/Bandeiras/Colômbia.png', 'América do Sul', '¡Oh, gloria inmarcesible! ¡Oh, júbilo inmortal! En surcos de dolores El bien germina ya', 'B');
INSERT INTO Selecao VALUES ('Equador', 'Seleção Equatoriana', 'TrabalhoFinalI/Etapa3/Bandeiras/Equador.png', 'América do Sul', '¡Salve, Oh Patria, mil veces! ¡Oh Patria Gloria a ti! ¡Gloria a ti! Ya tu pecho, tu pecho, rebosa Gozo y paz y a tu pecho rebosa Y tu frente, tu frente radiosa', 'C'); 
INSERT INTO Selecao VALUES ('Japão', 'Seleção Japonesa', 'TrabalhoFinalI/Etapa3/Bandeiras/Japão.png', 'Ásia', 'Kimigayo wa Chiyo ni yachiyo ni Sazare-ishi no Iwao to narite Koke no musu made', 'C');
INSERT INTO Selecao VALUES ('Paraguai', 'Seleção Paraguaia', 'TrabalhoFinalI/Etapa3/Bandeiras/Paraguai.png', 'América do Sul', 'A los pueblos de América, infausto Tres centurias un cetro oprimió Mas un día soberbia surgiendo "¡Basta!" —dijo, y el cetro rompió', 'B');
INSERT INTO Selecao VALUES ('Peru', 'Seleção Peruana', 'TrabalhoFinalI/Etapa3/Bandeiras/Peru.png', 'América do Sul', 'Somos libres Seámoslo siempre, seámoslo siempre Y antes niegue sus luces Sus luces, ¡sus luces el sol! Que faltemos al voto solemne Que la patria al eterno elevó', 'A');
INSERT INTO Selecao VALUES ('Uruguai', 'Seleção Uruguaia', 'TrabalhoFinalI/Etapa3/Bandeiras/Uruguai.png', 'América do Sul', 'Orientales la Patria o la Tumba! Libertad o con gloria morir! Es el voto que el alma pronuncia Y que heroicos sabremos cumplir!', 'C');
INSERT INTO Selecao VALUES ('Venezuela', 'Seleção Venezuelana', 'TrabalhoFinalI/Etapa3/Bandeiras/Venezuela.png', 'América do Sul', 'Gloria al bravo pueblo Que el yugo lanzó La ley respetando La virtud y honor', 'A');